module.exports = {
    PIPELINE : {
        FETCH_PIPELINES: 'FETCH_PIPELINES',
        FETCH_RUNNING_PIPELINES: 'FETCH_RUNNING_PIPELINES',
        FETCH_PIPELINE: 'FETCH_PIPELINE',
    },
    DEBUG : {
        LOG_INFO: 'LOG_INFO',
        LOG_DEBUG: 'LOG_DEBUG',
        LOG_WARN: 'LOG_WARN',
        LOG_ERROR: 'LOG_ERROR',
    },
    SAVE_CONFIG: 'SAVE_CONFIG',
    DELETE_CONFIG: 'DELETE_CONFIG',
    CLOSE_WINDOW: 'CLOSE_WINDOW',
};
